# Generated by Django 5.0.2 on 2024-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitConnect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='text',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(blank=True, height_field=200, max_length=200, upload_to='pfp/', width_field=200),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, height_field=200, max_length=200, upload_to='post_img/', width_field=200),
        ),
    ]
